packages:
  - "packages/*"
  - "test-project"
  - "site"
  - "examples/*"
allowBuilds:
  esbuild: false
  workerd: true

linkWorkspacePackages: true

overrides:
  "@types/hast": "3.0.5"
  satteri: "0.10.5"

patchedDependencies:
  "@astrojs/starlight@0.41.7": patches/@astrojs__starlight@0.41.7.patch
