[build]
command = "cd .. && npm i -g pnpm@6.11.5 && pnpm i --store-dir=site/node_modules/.pnpm-store && cd site && pnpm run build"
publish = "out"

[build.environment]
# This essentially means "don't run npm install" - https://github.com/netlify/build/issues/1633#issuecomment-873535715
NPM_FLAGS = "--prefix=./empty-for-netlify"
