[build]
command = "cd .. && npm i -g pnpm@6.11.5 && pnpm i --store-dir=site/node_modules/.pnpm-store && cd site && pnpm run build"
publish = "out"

[build.environment]
# This essentially means "don't run npm install" - https://community.netlify.com/t/using-pnpm-and-pnpm-workspaces/2759/10
NPM_FLAGS = "--prefix=/dev/null"
