name: "Setup Dependencies"
runs:
  using: "composite"
  steps:
    - run: corepack enable pnpm
      shell: bash

    - name: Setup Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        registry-url: "https://registry.npmjs.org"
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install
      shell: bash
