name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/setup-deps

      - name: Check Types
        run: pnpm run types
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/setup-deps

      - name: Linting
        run: pnpm run lint
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/setup-deps

      - name: Tests
        run: pnpm run test
