name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set Node.js 22.x
        uses: actions/setup-node@main
        with:
          node-version: 22.x

      - name: Install pnpm
        run: corepack enable pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Check Types
        run: pnpm run types
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set Node.js 22.x
        uses: actions/setup-node@main
        with:
          node-version: 22.x

      - name: Install pnpm
        run: corepack enable pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Linting
        run: pnpm run lint
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set Node.js 22.x
        uses: actions/setup-node@main
        with:
          node-version: 22.x

      - name: Install pnpm
        run: corepack enable pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Tests
        run: pnpm run test
