name: Publish (Preview)
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/setup-deps

      - name: Build
        run: pnpm build

      - run: pnpm dlx pkg-pr-new publish --compact --comment=off
