name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set Node.js 22.x
        uses: actions/setup-node@main
        with:
          node-version: 22.x

      - name: Install pnpm
        run: corepack enable pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: "Create Pull Request or Publish to npm"
        uses: changesets/action@master
        with:
          publish: pnpm run release
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
